### ISSUE TITLE
Will the code be released ? 

### ISSUE THREAD

**Issue by pipme** [orlitany/SelfSupervisedFMNet#1]
Hi, I'm very interested in your work and i'd like to ask whether the code will be released. If yes, when will it be and if not, I wonder I can probably modify from https://github.com/orlitany/DeepFunctionalMaps ?

Thanks.

**Comment by orlitany** [comment]
Thanks for your interest. Yes, we have made the code publicly available here: https://github.com/OshriHalimi/unsupervised_learning_of_dense_shape_correspondence
